-- =================================================================
-- DockShield DaaS — Supabase Schema
-- =================================================================
-- Run this in: Supabase Dashboard → SQL Editor → New Query → Run
-- =================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------
-- 1. LEADS TABLE — Populated by the 3D PWA frontend
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  email TEXT NOT NULL,
  address TEXT NOT NULL,
  lat NUMERIC,
  lng NUMERIC,
  dock_type TEXT DEFAULT 'fixed',
  status TEXT DEFAULT 'new',
  -- Status flow: new → quoted → active → churned
  CONSTRAINT valid_status CHECK (status IN ('new', 'quoted', 'active', 'churned'))
);

-- Index for email lookups and status filtering
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);

-- ---------------------------------------------------------------
-- 2. QUOTES TABLE — Generated by the auto-pipeline
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quotes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID REFERENCES leads(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  daas_tier INTEGER NOT NULL CHECK (daas_tier BETWEEN 1 AND 3),
  monthly_price NUMERIC NOT NULL CHECK (monthly_price > 0),
  stripe_payment_link TEXT,
  status TEXT DEFAULT 'pending',
  -- Status flow: pending → processing → link_generated → paid → expired
  CONSTRAINT valid_quote_status CHECK (status IN ('pending', 'processing', 'link_generated', 'paid', 'expired'))
);

CREATE INDEX IF NOT EXISTS idx_quotes_lead ON quotes(lead_id);
CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes(status);

-- ---------------------------------------------------------------
-- 3. CUSTOMERS TABLE — Activated post-payment via Stripe webhook
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  lead_id UUID REFERENCES leads(id) ON DELETE SET NULL,
  stripe_customer_id TEXT UNIQUE,
  active_tier INTEGER DEFAULT 0,
  service_schedule JSONB DEFAULT '{}',
  -- active_tier = 0 means cancelled/inactive
  CONSTRAINT valid_tier CHECK (active_tier BETWEEN 0 AND 3)
);

CREATE INDEX IF NOT EXISTS idx_customers_stripe ON customers(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_customers_active ON customers(active_tier) WHERE active_tier > 0;

-- ---------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
-- ---------------------------------------------------------------
-- Enable RLS on all tables
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

-- Leads: anon can INSERT (lead capture form), service_role can do everything
CREATE POLICY "anon_insert_leads" ON leads
  FOR INSERT TO anon
  WITH CHECK (true);

CREATE POLICY "service_role_all_leads" ON leads
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- Quotes: only service_role (Edge Functions use service_role key)
CREATE POLICY "service_role_all_quotes" ON quotes
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- Customers: only service_role
CREATE POLICY "service_role_all_customers" ON customers
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- ---------------------------------------------------------------
-- 5. ANALYTICS VIEW — Quick dashboard query
-- ---------------------------------------------------------------
CREATE OR REPLACE VIEW pipeline_summary AS
SELECT
  (SELECT COUNT(*) FROM leads) AS total_leads,
  (SELECT COUNT(*) FROM leads WHERE status = 'new') AS new_leads,
  (SELECT COUNT(*) FROM leads WHERE status = 'quoted') AS quoted_leads,
  (SELECT COUNT(*) FROM leads WHERE status = 'active') AS active_leads,
  (SELECT COUNT(*) FROM quotes WHERE status = 'paid') AS paid_quotes,
  (SELECT COUNT(*) FROM customers WHERE active_tier > 0) AS active_customers,
  (SELECT COALESCE(SUM(monthly_price), 0) FROM customers c JOIN quotes q ON c.lead_id = q.lead_id WHERE c.active_tier > 0 AND q.status = 'paid') AS monthly_recurring_revenue;
